plugins:
  - rubocop-erb

inherit_gem:
  rubocop-rails-omakase: rubocop.yml

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/IndentationConsistency:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Style/ColonMethodCall:
  Enabled: true

Style/MethodCallWithoutArgsParentheses:
  Enabled: false
